In [38]:
import numpy as np
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print('Vectorized version took: ' + str(1000*(toc-tic)) + 'ms')

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()
print(c)
print('Non-vectorized version took: ' + str(1000*(toc-tic)) + 'ms')

249604.110071
Vectorized version took: 0.8587837219238281ms
249604.110071
Non-vectorized version took: 378.53217124938965ms


In [40]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])
print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [49]:
cal = A.sum(axis=0)
A = 100 * A / cal # broadcasting
A

array([[ 94.91525424,   0.        ,   2.83140283,  88.42652796],
       [  2.03389831,  43.51464435,  33.46203346,  10.40312094],
       [  3.05084746,  56.48535565,  63.70656371,   1.17035111]])

In [55]:
img = np.random.randn(32,32,3)
img.reshape(32*32*3,1).shape

(3072, 1)

In [71]:
a = np.random.randint(9, size=(3, 3))
b = np.random.randint(3, size=(3, 1))
c = a * b
print(a)
print(b)
print(c)

[[2 6 3]
 [7 0 6]
 [2 6 6]]
[[2]
 [1]
 [0]]
[[ 4 12  6]
 [ 7  0  6]
 [ 0  0  0]]
